# Generated by Django 4.2.9 on 2026-01-15 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Target name or identifier", max_length=255
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP Address"),
                            ("url", "URL"),
                            ("subnet", "Subnet"),
                        ],
                        default="domain",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Domain, IP, or URL", max_length=500, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
                "ordering": ["-created_at"],
            },
        ),
    ]
