# Generated by Django 4.2.9 on 2026-01-15 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief, descriptive title of the vulnerability",
                        max_length=500,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sqli", "SQL Injection"),
                            ("xss", "Cross-Site Scripting"),
                            ("ssrf", "Server-Side Request Forgery"),
                            ("xxe", "XML External Entity"),
                            ("rce", "Remote Code Execution"),
                            ("lfi", "Local File Inclusion"),
                            ("rfi", "Remote File Inclusion"),
                            ("idor", "Insecure Direct Object Reference"),
                            ("broken_auth", "Broken Authentication"),
                            ("sensitive_data", "Sensitive Data Exposure"),
                            ("xxe", "XML External Entity"),
                            ("broken_access", "Broken Access Control"),
                            ("security_misconfig", "Security Misconfiguration"),
                            (
                                "using_known_vulnerable",
                                "Using Components with Known Vulnerabilities",
                            ),
                            (
                                "insufficient_logging",
                                "Insufficient Logging & Monitoring",
                            ),
                            ("csrf", "Cross-Site Request Forgery"),
                            ("open_redirect", "Open Redirect"),
                            ("clickjacking", "Clickjacking"),
                            ("cors_misconfig", "CORS Misconfiguration"),
                            ("missing_headers", "Missing Security Headers"),
                            ("ssl_tls", "SSL/TLS Issues"),
                            ("info_disclosure", "Information Disclosure"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of vulnerability",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="info",
                        help_text="Severity level of the finding",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("confirmed", "Confirmed"),
                            ("false_positive", "False Positive"),
                            ("accepted_risk", "Accepted Risk"),
                            ("fixed", "Fixed"),
                            ("retest", "Needs Retest"),
                        ],
                        default="new",
                        help_text="Current remediation status",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed explanation of the vulnerability"
                    ),
                ),
                (
                    "affected_url",
                    models.URLField(
                        blank=True,
                        help_text="URL where the vulnerability was found",
                        max_length=1000,
                    ),
                ),
                (
                    "affected_parameter",
                    models.CharField(
                        blank=True,
                        help_text="Vulnerable parameter name (if applicable)",
                        max_length=500,
                    ),
                ),
                (
                    "proof_of_concept",
                    models.TextField(
                        blank=True,
                        help_text="Steps to reproduce or exploit the vulnerability",
                    ),
                ),
                (
                    "http_request",
                    models.TextField(
                        blank=True, help_text="Raw HTTP request demonstrating the issue"
                    ),
                ),
                (
                    "http_response",
                    models.TextField(
                        blank=True,
                        help_text="Raw HTTP response showing the vulnerability",
                    ),
                ),
                (
                    "discovered_by",
                    models.CharField(
                        blank=True,
                        help_text="Security tool that found this issue (e.g., 'nmap', 'sqlmap', 'nuclei')",
                        max_length=100,
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="CVSS 3.1 score (0.0 - 10.0)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "cvss_vector",
                    models.CharField(
                        blank=True, help_text="CVSS 3.1 vector string", max_length=200
                    ),
                ),
                (
                    "remediation",
                    models.TextField(
                        blank=True, help_text="Steps to fix this vulnerability"
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True,
                        help_text="External links, CVEs, or documentation (one per line)",
                    ),
                ),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to screenshot evidence file",
                        max_length=500,
                    ),
                ),
                (
                    "evidence_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to additional evidence files",
                        max_length=500,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this finding was discovered",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this finding was manually verified",
                        null=True,
                    ),
                ),
                (
                    "fixed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this vulnerability was remediated",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this finding"
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        help_text="The scan that discovered this finding",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="scans.scan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finding",
                "verbose_name_plural": "Findings",
                "ordering": ["-severity", "-discovered_at"],
                "indexes": [
                    models.Index(
                        fields=["severity"], name="findings_fi_severit_95e77d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="findings_fi_status_8e463e_idx"
                    ),
                    models.Index(
                        fields=["category"], name="findings_fi_categor_d4d912_idx"
                    ),
                    models.Index(
                        fields=["-discovered_at"], name="findings_fi_discove_a3927a_idx"
                    ),
                ],
            },
        ),
    ]
