# Generated by Django 4.2.9 on 2026-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("findings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                help_text="Additional structured data from security tools (JSON format). Examples: SQLMap databases/tables, nuclei matched patterns, etc.",
                null=True,
            ),
        ),
    ]
